[frontend]
darlavinaykumar.fun

[local]
localhost

[local:vars]
name=Iam from Inventory file
Role=DevOps Engineer  
Skills=Ansible
Experience=4 years

[mongodb]
mongodb.darlavinaykumar.fun

[redis]
redis.darlavinaykumar.fun

[mysql]
mysql.darlavinaykumar.fun

[catalogue]
catalogue.darlavinaykumar.fun

[user]
user.darlavinaykumar.fun

[cart]
cart.darlavinaykumar.fun

[shipping]
shipping.darlavinaykumar.fun

[payment]
payment.darlavinaykumar.fun

[rabbitmq]
rabbitmq.darlavinaykumar.fun

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
