MONGODB_HOST: "mongodb.darlavinaykumar.fun"
REDIS_HOST: "redis.darlavinaykumar.fun"
MYSQL_HOST: "mysql.darlavinaykumar.fun"
RABBITMQ_HOST: "rabbitmq.darlavinaykumar.fun"
USER_HOST: "user.darlavinaykumar.fun"
CART_HOST: "cart.darlavinaykumar.fun"
PAYMENT_HOST: "payment.darlavinaykumar.fun"
SHIPPING_HOST: "shipping.darlavinaykumar.fun"
CATALOGUE_HOST: "catalogue.darlavinaykumar.fun"