- name: user creation with error handling
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: check user exist or not
      ansible.builtin.command: id roboshop
      register: user_output
      ignore_errors: yes
    
    - name: print the output of command
      ansible.builtin.debug:
        msg: "{{ user_output }}"
    
    - name: create user if not exist
      ansible.builtin.command: useradd roboshop
      when: user_output.rc != 0